In [1]:
import pandas as pd
import numpy as np
# Set random seed for reproducibility
np.random.seed(42)
# Generate 1000 rows with 4 columns
n_rows = 1000
data = {
    'color': np.random.choice(['red', 'blue', 'green'], n_rows),
    'size': np.random.choice(['small', 'medium', 'large'], n_rows),
    'material': np.random.choice(['plastic', 'metal', 'wood'], n_rows),
    'price': np.random.randint(10, 500, n_rows)
}
df = pd.DataFrame(data)

# Display first few rows
print(df.head())
print(f"\nDataset shape: {df.shape}")

   color   size material  price
0  green  large    metal    423
1    red  large  plastic    351
2  green  large  plastic    229
3  green  large     wood    400
4    red  small  plastic    172

Dataset shape: (1000, 4)


In [2]:
df.head()

,color,size,material,price
0,green,large,metal,423
1,red,large,plastic,351
2,green,large,plastic,229
3,green,large,wood,400
4,red,small,plastic,172


In [3]:
# pip install category_encoders

In [4]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder
from category_encoders import TargetEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


In [5]:
X = df.drop(columns='price')
y= df.price
xtrain,xtest,ytrain,yest = train_test_split(X,y,train_size=0.8,random_state=42)

In [6]:
label_encoder = LabelEncoder()
''' 
# updated_xtrain = label_encoder.fit_transform(xtrain)
ValueError: y should be a 1d array, 
got an array of shape (800, 3) instead.

'''

' \n# updated_xtrain = label_encoder.fit_transform(xtrain)\nValueError: y should be a 1d array, \ngot an array of shape (800, 3) instead.\n\n'

In [7]:
label_encoder.fit_transform(xtrain['color'])

array([1, 0, 0, 2, 1, 1, 2, 1, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 1, 2, 0, 1,
       2, 0, 2, 1, 1, 1, 1, 2, 2, 0, 0, 2, 0, 1, 2, 2, 2, 1, 1, 0, 2, 1,
       2, 0, 1, 1, 2, 2, 0, 1, 0, 0, 1, 1, 1, 1, 0, 2, 2, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 2, 0, 1, 0, 2, 2, 2, 2,
       1, 1, 2, 2, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 2, 1, 2,
       2, 1, 1, 1, 1, 0, 1, 1, 2, 1, 0, 2, 2, 2, 2, 2, 1, 0, 0, 0, 2, 1,
       2, 0, 1, 0, 1, 0, 2, 1, 0, 0, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 0, 2,
       2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 0, 1, 1, 2, 2, 0, 0, 0, 1, 0, 1, 1,
       2, 0, 1, 1, 1, 1, 2, 2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 2, 1, 1, 1, 0,
       0, 1, 2, 0, 0, 0, 0, 2, 0, 2, 2, 1, 1, 1, 2, 0, 1, 0, 0, 0, 2, 1,
       0, 0, 0, 1, 0, 1, 2, 2, 0, 2, 1, 0, 2, 0, 2, 2, 0, 0, 1, 2, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 2, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 2, 0, 2, 0, 0, 2, 1, 2, 2, 2, 0, 1, 2, 1, 0, 2, 1, 0, 1, 2,
       1, 1, 2, 2, 2, 2, 2, 1, 0, 2, 0, 0, 1, 2, 2,

In [8]:
# label_encoder.transform(xtest)

In [9]:
#new_input
new_input = ['red','red']
label_encoder.transform(new_input)

array([2, 2])

In [10]:
xtrain

,color,size,material
29,green,small,wood
535,blue,medium,metal
695,blue,small,wood
557,red,small,plastic
836,green,large,plastic
...,...,...,...
106,red,large,plastic
270,red,small,plastic
860,blue,large,plastic
435,blue,small,plastic


In [11]:
#OneHotEncoder()
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
values = encoder.fit_transform(xtrain)
#toarray()
values = values.toarray()
values

array([[0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]], shape=(800, 9))

In [12]:
encoder = OneHotEncoder(sparse_output=False)
values = encoder.fit_transform(xtrain)
values

array([[0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]], shape=(800, 9))

In [13]:
columns = encoder.get_feature_names_out()

In [14]:
pd.DataFrame(values,columns=columns)

,color_blue,color_green,color_red,size_large,size_medium,size_small,material_metal,material_plastic,material_wood
0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
4,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...
795,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
796,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
797,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
798,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0


In [15]:
''' 
encoder.transform(xtest[['color','size']])
ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- material
'''
encoder.transform(xtest) #Valid why ? xtest is 2-D


array([[0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]], shape=(200, 9))

In [16]:
''' 
new_input = [['red','large'],['blue','small']]
encoder.transform(new_input)
ValueError: X has 2 features, 
but OneHotEncoder is expecting 3 features as input.
'''

" \nnew_input = [['red','large'],['blue','small']]\nencoder.transform(new_input)\nValueError: X has 2 features, \nbut OneHotEncoder is expecting 3 features as input.\n"

In [18]:
# new_input = [['red1','large','plastic'],['blue','small','wood']]
# encoder.transform(new_input)
# ''' 
# ValueError: Found unknown categories ['red1'] in column 0
# during transform

# '''

In [19]:
encoder = OneHotEncoder(sparse_output=False,handle_unknown='ignore')
updated_xtrain = encoder.fit_transform(xtrain)

new_input = [['red1','large1','plastic'],['blue','small','wood']]
encoder.transform(new_input)

c:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.]])

In [ ]:
encoder.get_feature_names_out()

array(['color_blue', 'color_green', 'color_red', 'size_large',
       'size_medium', 'size_small', 'material_metal', 'material_plastic',
       'material_wood'], dtype=object)

### OrdinalEncoder

In [25]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()
updated_xtrain = encoder.fit_transform(xtrain)
# updated_xtrain

'''
updated_xtrain = encoder.fit_transform(xtrain['color'])
ValueError: Expected a 2-dimensional container
but got <class 'pandas.core.series.Series'> instead. 
Pass a DataFrame containing a single row 
(i.e. single sample) or a single column (i.e. single feature)
instead.

'''
updated_xtrain

array([[1., 2., 2.],
       [0., 1., 0.],
       [0., 2., 2.],
       ...,
       [0., 0., 1.],
       [0., 2., 1.],
       [1., 2., 1.]], shape=(800, 3))

In [23]:
encoder.get_feature_names_out()

array(['color', 'size', 'material'], dtype=object)

In [28]:
updated_xtest = encoder.transform(xtest)
''' 
updated_xtest = encoder.transform(xtest['color'])
ValueError: Expected a 2-dimensional container
but got <class 'pandas.core.series.Series'> instead. 
Pass a DataFrame containing a single row 
(i.e. single sample) or a single column (i.e. single feature)
instead.
'''
updated_xtest

array([[2., 2., 0.],
       [2., 2., 0.],
       [0., 2., 0.],
       [1., 2., 1.],
       [0., 1., 0.],
       [2., 0., 1.],
       [1., 0., 1.],
       [2., 2., 1.],
       [2., 0., 0.],
       [0., 2., 0.],
       [0., 2., 0.],
       [0., 0., 0.],
       [2., 0., 1.],
       [0., 1., 2.],
       [1., 2., 0.],
       [2., 0., 0.],
       [1., 1., 2.],
       [2., 0., 1.],
       [2., 0., 2.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 2., 1.],
       [0., 1., 1.],
       [2., 1., 1.],
       [0., 1., 2.],
       [1., 0., 0.],
       [2., 2., 0.],
       [0., 2., 0.],
       [1., 1., 1.],
       [2., 1., 0.],
       [2., 0., 2.],
       [0., 2., 0.],
       [1., 2., 0.],
       [0., 1., 0.],
       [0., 0., 2.],
       [2., 2., 2.],
       [2., 1., 1.],
       [2., 1., 0.],
       [1., 0., 0.],
       [2., 2., 2.],
       [2., 1., 2.],
       [1., 0., 0.],
       [2., 0., 1.],
       [0., 0., 1.],
       [1., 0., 2.],
       [1., 0., 2.],
       [1., 2

In [31]:
xtrain

,color,size,material
29,green,small,wood
535,blue,medium,metal
695,blue,small,wood
557,red,small,plastic
836,green,large,plastic
...,...,...,...
106,red,large,plastic
270,red,small,plastic
860,blue,large,plastic
435,blue,small,plastic


In [ ]:
# encoder = OrdinalEncoder(handle_unknown='error')
encoder = OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1)
updated_xtrain = encoder.fit_transform(xtrain)
updated_xtest = encoder.transform(xtest)
new_data = [['white','small','wood'],['red','small','wood']]
# new_data = pd.DataFrame(data=[['white','small','wood'],['red','small','wood']],columns=['color','size','material'])
updated_new_data = encoder.transform(new_data)
updated_new_data

c:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[-1.,  2.,  2.],
       [ 2.,  2.,  2.]])

In [36]:
xtrain['color'].unique()

array(['green', 'blue', 'red'], dtype=object)

In [37]:
xtrain

,color,size,material
29,green,small,wood
535,blue,medium,metal
695,blue,small,wood
557,red,small,plastic
836,green,large,plastic
...,...,...,...
106,red,large,plastic
270,red,small,plastic
860,blue,large,plastic
435,blue,small,plastic


In [ ]:
''' 
encoder = OrdinalEncoder(categories=[['green', 'blue', 'red']],handle_unknown='use_encoded_value',unknown_value=-1)
encoder.fit_transform(xtrain)
ValueError: Shape mismatch: 
if categories is an array, 
it has to be of shape (n_features,).
why ? 
xtrain is having 3 cols and categories=[[col_order]]
shape mismatching
when xtrain cols == col_orders
'''

" \nencoder = OrdinalEncoder(categories=[['green', 'blue', 'red']],handle_unknown='use_encoded_value',unknown_value=-1)\nencoder.fit_transform(xtrain)\nValueError: Shape mismatch: \nif categories is an array, \nit has to be of shape (n_features,).\nwhy ? \nxtrain is having 3 cols and categories=[[col_order]]\nshape mismatching\n"

In [ ]:
encoder = OrdinalEncoder(categories=[['green', 'blue', 'red']],handle_unknown='use_encoded_value',unknown_value=-1)
